development:
      cloud_name: darjfu5u1
      api_key: 635357462542361
      api_secret: 5NZsyJ3alIyuRGy5pw18qmDay_A
      secure: true
    production:
      cloud_name: darjfu5u1
      api_key: 635357462542361
      api_secret: 5NZsyJ3alIyuRGy5pw18qmDay_A
      secure: true